### PR TITLE
Switch to go 1.14 and update modules

### PR DESCRIPTION
**Pull request by saschagrunert**
Go 1.13 will be EOL from the beginning of August (release of go 1.15). I
take the opportunity to update the CI as well as the modules.

### CODE REVIEW

**Comment by saschagrunert** [comment]
The CircleCI integration does not work any more, right? It is still building, but I think we might have to re-link the repository https://app.circleci.com/pipelines/github/seccomp/containers-golang

**Comment by rhatdan** [comment]
LGTM
@giuseppe @vrothberg PTAL

**Comment by vrothberg** [comment]
LGTM but let's first get the CI back. Merging "blindly" gives me bad karma :^)

**Comment by saschagrunert** [comment]
Can someone with administrative permissions have a look on this? :innocent:

**Comment by vrothberg** [comment]
I think @rhatdan has almighty powers all over GitHub :muscle:

**Comment by rhatdan** [comment]
No even my powers can not compare to @pcmoore at least over github.com/seccomp

@pcmoore Could you add CircleCI https://github.com/seccomp/containers-golang/pull/30#issuecomment-661765082

**Comment by pcmoore** [comment]
> @pcmoore Could you add CircleCI [#30 (comment)](https://github.com/seccomp/containers-golang/pull/30#issuecomment-661765082)

Should be all set now, let me know if it isn't working.

**Comment by rhatdan** [comment]
Thanks @pcmoore

**Pull request merged**
