### PR TITLE
Switch whilelist to allowlist

### PR DESCRIPTION
**Pull request by rhatdan**
We want to move to more enclusive names/terms in our code, and remove problematic language
from code and comments.

We want to change reference for whitelist/blacklist to allowlist/denylist.

https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@ashley-cui FYI

**Comment by rhatdan** [comment]
@giuseppe @vrothberg PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks @rhatdan

**Pull request merged**
