### PR TITLE
add seccomp.json

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

copied the file from skopeo rpm dist-git
https://src.fedoraproject.org/rpms/skopeo/blob/master/f/seccomp.json

@mheon PTAL.

### CODE REVIEW

**Comment by pcmoore** [comment]
Wait a minute, this JSON file includes policy doesn't it?  If that is the case, NACK from me, the core upstream libseccomp library and bindings should be policy-free.

**Comment by rhatdan** [comment]
@pcmoore What do you think about moving the golang bindings out of libseccomp into github.com/containers/seccomp?  Then we can manage it independently of libseccomp?

**Comment by pcmoore** [comment]
NACK on that idea too.  I realize it's hard to believe, but the world is bigger than containers :) and I would like to make sure there is a set of golang bindings that don't assume a specific use case.

**Comment by rhatdan** [comment]
Then change the name of the repo.  containers-golang does make it seem like they are for containers.

**Comment by pcmoore** [comment]
Ooof.  Sorry guys.  I didn't look closely enough at the repo name, I thought this was a PR for libseccomp-golang.

You can ignore all of my comments in this thread :)

**Comment by lsm5** [comment]
So, does this look good for merge? /cc @mheon

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
